### ISSUE TITLE
Download timeout too low

### ISSUE THREAD

**Issue by dabreegster** [ITSLeeds/osmextract#143]
Hi! I'm getting a crash when running `osmextract::oe_get(place = "west yorkshire")`:

```
Error in utils::download.file(url = file_url, destfile = file_path, mode = "wb",  : 
  download from 'https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf' failed
Calls: <Anonymous> -> oe_read -> oe_download -> <Anonymous>
In addition: Warning messages:
1: st_crs<- : replacing crs does not reproject data; use st_transform for that 
2: In utils::download.file(url = file_url, destfile = file_path, mode = "wb",  :
  downloaded length 14860288 != reported length 33826429
3: In utils::download.file(url = file_url, destfile = file_path, mode = "wb",  :
  URL 'https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf': Timeout of 60 seconds was reached
```

In the 60s timeout, my connection only grabbed about 15MB of the file. I'm new to R and am having trouble figuring out where `utils::download.file` is actually defined. Where's the appropriate place to add a timeout? Also, could the underlying HTTP fetcher possibly be changed to one that includes a progress bar and shows the total file size, to reassure users on slower connections?

Thanks!

**Comment by agila5** [comment]
Hi @dabreegster! 

Could you try running the following code:  `osmextract::oe_get("west yorkshire", quiet = FALSE, force_download = TRUE)` ? The argument `quiet = FALSE` should print some (hopefully) informative messages, while the parameter `force_download = TRUE` will force the (re)download of the `.osm.pbf` file in case something wrong happened during an old download process. 

This is the output on my laptop: 

``` r
osmextract::oe_get("west yorkshire", quiet = FALSE, force_download = TRUE)
#> The input place was matched with: West Yorkshire
#> File downloaded!
#> The corresponding gpkg file was already detected. Skip vectortranslate operations.
#> Reading layer `lines' from data source `C:\Users\Utente\Documents\osm_data\geofabrik_west-yorkshire-latest.gpkg' using driver `GPKG'
#> Simple feature collection with 3860 features and 9 fields
#> geometry type:  MULTILINESTRING
#> dimension:      XY
#> bbox:           xmin: -1.786844 ymin: 53.70248 xmax: -1.291864 ymax: 53.94313
#> geographic CRS: WGS 84
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> Where's the appropriate place to add a timeout?

I'm not sure about the timeout problem but I think that this is caused by an old `.pbf` file that was previously downloaded. It should be fixed using `force_download = TRUE`. 

> Also, could the underlying HTTP fetcher possibly be changed to one that includes a progress bar and shows the total file size, to reassure users on slower connections?

If you set `quiet = FALSE` (the default value is `TRUE`), you should see some messages (and a progress bar in interactive mode) that report the status of the download process.

**Comment by Robinlovelace** [comment]
Follow-up comment: maybe we should rethink this setting:

https://github.com/ITSLeeds/osmextract/blob/4fafa757fe0c7f701bd1b4833113346843ed6b1a/R/download.R#L136

I like the fact that we have a blanket `quiet` argument but think there is a reasonable 'argument' for either creating a new argument, e.g. called `quiet_download` or simply removing that line so that `download.file()`'s default sensibly chatty output continues. Are there really any use cases when people will want to override that?

**Comment by dabreegster** [comment]
> If you set quiet = FALSE (the default value is TRUE), you should see some messages (and a progress bar in interactive mode) that report the status of the download process.

Ah, `quiet = FALSE` is much better, thanks!

> Are there really any use cases when people will want to override that?

I'm not sure what conventions are in R workflows, but a bit more verbosity seems nice. If executing anything on a command line takes more than a few seconds, as a user, I'd prefer to know what's happening.

> I'm not sure about the timeout problem but I think that this is caused by an old .pbf file that was previously downloaded. It should be fixed using force_download = TRUE.

I've set `OSMEXT_DOWNLOAD_DIRECTORY` and have tried deleting the file in between runs, but the 60s timeout is still happening. I've figured out that [download.file](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/download.file) is part of the stdlib, and I'm using [options](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/options) to change the default. The question for this bug becomes, is it appropriate for this library to set a custom timeout, or should the application be responsible for that?

**Comment by agila5** [comment]
> I'm not sure what conventions are in R workflows, but a bit more verbosity seems nice. If executing anything on a command line takes more than a few seconds, as a user, I'd prefer to know what's happening.

First of all, thank you very much @dabreegster for your feedbacks. We are still working on the first version of the package and we still need to polish a lot of default values. The idea behind `quiet = TRUE` was to turn on/off all messages at the same time, but this is probably not ideal. @Robinlovelace: I think that we could force printing of some messages (i.e. "start download" + progress bar in interactive mode, "start vectortranslate" + progress bar in interactive mode) while all the other messages are optional. 

> I've set OSMEXT_DOWNLOAD_DIRECTORY and have tried deleting the file in between runs, but the 60s timeout is still happening. I've figured out that download.file is part of the stdlib, and I'm using options to change the default.

I think I've never faced that problem, and I didn't know about the `timeout` option in `download.file`. What happens when you run the following? 

``` r
options(timeout = 240) # or even bigger value
osmextract::oe_get("west yorkshire", quiet = FALSE, force_download = TRUE, force_vectortranslate = TRUE)
```

And what happens when you try downloading the [same](https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf) file manually from Geofabrik servers? Maybe this is not a problem related to R, but this is a problem related to Geofabrik. If that's the case, you may try running: 

``` r
osmextract::oe_get("yorkshire and the humber", provider = "openstreetmap_fr", quiet = FALSE)
```
with or without the new value for `timeout`. That's not exactly equal to the previous OSM data but, unfortunately, the West Yorkshire region is defined only by Geofabrik. 

> The question for this bug becomes, is it appropriate for this library to set a custom timeout, or should the application be responsible for that? 

I'm not sure what the "best practices" are for these casee, but I wouldn't modify the `timeout` value set by R. Maybe we can think of a better error message but I'm not sure since everything is happening inside `download.file()`. @Robinlovelace ?

**Comment by dabreegster** [comment]
> I think I've never faced that problem, and I didn't know about the timeout option in download.file. What happens when you run the following?

Setting a higher timeout works fine; I'm able to complete the example successfully.

> And what happens when you try downloading the same file manually from Geofabrik servers? 

It's about the same speed with `wget` or `curl` manually. The problem is my wifi connection upstairs, plus sometimes my ISP flaking out. The 60s default timeout is too low for some OSM files -- `china-latest.osm.pbf` from geofabrik is about 600MB; you have a pretty nice connection if you can grab that in under a minute. :)  This feels like a more general issue with R's `download.file`, and I'm not sure what the best response is.

At the very least, maybe just adding a hint to the readme about `options(timeout = 300)` if you get the error. I can send a PR to update those docs if y'all determine that's the best course of action.

**Comment by agila5** [comment]
> At the very least, maybe just adding a hint to the readme about options(timeout = 300) if you get the error. I can send a PR to update those docs if y'all determine that's the best course of action.

That would be great, thanks! I would like creating a "troubleshooting vignette" sooner or later but I think that, for the moment, you can simply add a message in the README
